version: '3.5'
services:

  rabbitmq:
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    container_name: elk-rabbit
    image: elk-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - elk-network
      
networks:
  elk-network:
    name: elk-network
    driver: bridge
